
# Fetch All
Get http://localhost:3001/api/users


###
POST http://localhost:3001/api/users
content-type : application/json

{
    "username": "joe",
    "email": "joe@gmail.com",
    "password": "password1234"
}